name: Ejemplo CI/CD

on:
  push:

jobs:
    inicio:
        runs-on: windows-latest
        steps:
            - name: mostrar texto
              run: echo "Paso para clonar respositorio a github actions"
            - name: clonar repositorio
              uses: actions/checkout@v4.2.2

    build:
        runs-on: windows-latest
        needs: [inicio]
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo 2"
    
    test:
        runs-on: windows-latest
        needs: [build]
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo 3"

    deploy:
        runs-on: windows-latest
        needs: [test]
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo 4"