name: Ejemplo CI/CD

on:
  push:

jobs:
    inicio:
        runs-on: macos-latest
        steps:
            - name: mostrar texto
              run: echo "Paso para clonar respositorio a github actions"
            - name: clonar repositorio
              uses: actions/checkout@v4.2.2

    build:
        runs-on: macos-latest
        needs: [inicio]
        steps:
            - name: texto
              run: echo "Construir"
            - name: instalar PHP y composer MacOS
              run: |
                brew update
                brew install php composer
                php -v
                composer --version 
            - name: Instalar MySql
              run: |
                brew install mysql
                brew services start mysql
                sleep 10  # Esperar 10 segundos para asegurarse de que MySQL inicia correctamente
                mysqladmin -u root password "root"
                mysql -u root -proot -e "CREATE DATABASE lumen_db;"
                
    
    test:
        runs-on: macos-latest
        needs: [build]
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo 3"

    deploy:
        runs-on: macos-latest
        needs: [test]
        steps:
            - name: mostrar texto
              run: echo "Hola Mundo 4"