name: Ejemplo CI/CD

on: 
   push:

jobs:
    inicio:
        runs-on: macos-lastest
        #Pasos:
        steps:
        - name: mostrar texto
          run: echo "Hola mundo"
    
    bluid:
        runs-on: macos-lastest
        needs: [inicio]
        steps:
        - name: mostrar texto
          run: echo "Construir"
